---
title: "Progress Memo 2"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Sheena Tan"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/final-project-1-sheena-tan.git](https://github.com/stat301-1-2023-fall/final-project-1-sheena-tan.git)

:::

## Updated Data Memo

### Data Source

I am using data from Northwestern's Course and Teacher Evaluation Council (CTEC) system, which is data available to students at Northwestern University. These evaluations provide ratings made by previous students regarding various courses and their instructor, including information like how much time the student spent on the course, what degree requirements the course fulfilled for the student, what year and school the student is in, and how they would rate the instruction and the course across several categories. 

As discussed with Professor Sass, I finished scraping data from the most recent academic year (2022-23) across various undergraduate courses, organizing the data by school and department. I took data from six representative departments, for each of the six Northwestern schools. 

1. Psychology (PSYCH) for Weinberg,
2. Civil and Environmental Engineering (CIV_ENV) for McCormick,
3. Music (MUSIC) for Bienen, 
4. Communication Studies (COMMS) for the School of Communications,
5. Journalism (JOUR) for Medill,
6. and School of Education & Social Policy Core (SESP) for SESP.

The data has a total of 5137 objects across 12 variables.

1. `school`: categorical variable; the school the department is from, coded `mcmk` for McCormick, `jour` for Medill, `comm` for Comms, `bien` for Bienen, `sesp` for SESP, and `wnbg` for Weinberg
2. `dept`: categorical variable; the department the course is offered through, coded `psych` for Psychology, `sesp` for SESP Core, `music` for Music, `comm_st` for Communication Studies , `jour` for Journalism, and `civ_env` for Civil and Environmental Engineering
3. `course_num`: the three digit course number
4. `course_term`: categorical variable; the quarter the course was offered, coded `fall` for Fall 2022, `winter` for Winter 2023, and `spring` for Spring 2023
5. `instructor`: the name of the instructor
6. `inst_rating`: the mean of students' responses to the prompt, "Provide an overall rating of the instruction." rated out of 6
7. `course_rating`: the mean of students' responses to the prompt, "Provide an overall rating of the course" rated out of 6
8. `learn_rating`: the mean of students' responses to the prompt, "Estimate how much you learned in the course." rated out of 6
9. `challenge_rating`: the mean of students' responses to the prompt, "Rate the effectiveness of the course in challenging you intellectually." rated out of 6
10. `interest_rating`: the mean of students' responses to the prompt, "Rate the effectiveness of the instructor in stimulating your interest in the subject." rated out of 6
11. `hours_spent`: the mean of students' reponses to the prompt, "Estimate the average number of hours per week you spent on this course outside of class and lab time."
12. `essay`: text responses to the prompt, "Please summarize your reaction to this course focusing on the aspects that were most important to you."

```{r}
# install packages
library(tidyverse)

# read in data
ctec_data_raw <- read.csv("data/ctec_data.csv")

# data cleaning
ctec_data <- ctec_data_raw |> 
  # consider empty strings as missing values
  mutate(
    school = na_if(school, ""),
    dept = na_if(dept, ""),
    course_term = na_if(course_term, ""),
    instructor = na_if(instructor, "")
  ) |> 
  # fill in missing values from the nearest value above
  fill(school, dept, course_num, course_term, instructor, inst_rating, 
       course_rating, learn_rating, challenge_rating, interest_rating, 
       hours_spent, .direction = "down")

```

